language: node_js
node_js:
  - 18  # Selecciona la versión de Node.js que necesitas

cache:
  directories:
    - node_modules

install:
  - npm install  # Instala las dependencias de tu proyecto

script:
  - ng test --watch=false --browsers=ChromeHeadless  # Comando para ejecutar las pruebas unitarias de Angular