version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:18.18.0  # Selecciona la versión de Node.js que necesitas

    working_directory: ~/repo

    steps:
      - checkout

      # Configura Node.js y Angular CLI
      - run:
          name: Install Dependencies
          command: |
            npm install -g @angular/cli
            npm install

      # Ejecuta las pruebas unitarias
      - run:
          name: Run Unit Tests
          command: ng test --watch=false --browsers=ChromeHeadless

workflows:
  version: 3
  build:
    jobs:
      - build